language: node_js
sudo: false
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codecov
script:
  - istanbul cover _mocha -- -R spec
  - codecov
node_js:
  - "8"
  - "--lts"
  - "node"
